### PR TITLE
Add authentication

### PR DESCRIPTION
**Pull request by grafitto**
### How to use:
```javascript
import { Client } from '@surix/client';

const client = new Client({
//Settings
})

client.authenticate({
    email: 'some email',
    password: 'some password'
}).then((authenticatedClient: Client) => {
    // Do something
})

// or

await client.authenticate({
    email: 'some email'
    password: 'some password'
})

// Then continue using client
```

### Related issues
#5

### CODE REVIEW

**Comment by habbes** [comment]
@grafitto does this implement API Key authentication?

**Comment by habbes** [comment]
Also, I wonder whether it wouldn't be a better idea for the API to lazily call `authenticate()` on its own. What I mean is, the user could specify the credentials in the options passed to the `Client` constructor. And then authentication would be performed the first time an API call is made.

**Comment by habbes** [comment]
Hmm, but then again, we don't need to do this with API keys, since API keys are transported with each request.

**Comment by grafitto** [comment]
> Also, I wonder whether it wouldn't be a better idea for the API to lazily call `authenticate()` on its own. What I mean is, the user could specify the credentials in the options passed to the `Client` constructor. And then authentication would be performed the first time an API call is made.

Very nice idea. Making the changes

**Comment by grafitto** [comment]
I have replaced the authentication with api key authentication:

How to use:
```javascript
import { Client }  from '@surix/client';

const client = new Client({ 
    baseUrl: 'http://localhost:5000/api',
    keyId: 'your key id',
    keySecret: 'your secret key'
});

// Use client normally
```

**Pull request merged**
